### ISSUE TITLE
Flash colors when data is updated

### ISSUE THREAD

**Issue by pawiromitchel** [pawiromitchel/Gas-Tracker#1]

**Comment by N3RDCLASH** [comment]
### Minimum Viable Product 

[Vue 2 Version](https://github.com/pawiromitchel/Gas-Tracker/pull/2 )
[Vue 3 Version](https://github.com/pawiromitchel/Gas-Tracker/pull/3)

[Live Version ](https://n3rdclash.github.io/Gas-Tracker/)

**Comment by pawiromitchel** [comment]
Thanks bro! Merged! 🤗🤗
